services:
  relayer:
    build:
      context: ./openzeppelin-relayer
      dockerfile: Dockerfile.development
    ports:
      - "8080:8080/tcp"
    environment:
      REDIS_URL: redis://redis:6379
      RATE_LIMIT_REQUESTS_PER_SECOND: 10
      RATE_LIMIT_BURST: 50
      WEBHOOK_SIGNING_KEY: ${WEBHOOK_SIGNING_KEY}
      API_KEY: ${API_KEY}
      KEYSTORE_PASSPHRASE: ${KEYSTORE_PASSPHRASE}
    security_opt:
      - no-new-privileges
    networks:
      - relayer-network
    volumes:
      - ./config:/app/config/
    depends_on:
      - redis
    restart: on-failure:5

  redis:
    image: redis:bookworm
    security_opt:
      - no-new-privileges
    volumes:
      - redis_data:/data
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --save
      - "60"
      - "1"
    networks:
      - relayer-network
    restart: on-failure:5

networks:
  relayer-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
